# Generated by Django 5.1.7 on 2025-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_confirmacao_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='convidados_qrcodes/'),
        ),
    ]
