# Generated by Django 5.1.7 on 2025-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_confirmacao_convidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
