# Generated by Django 5.1.7 on 2025-03-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_convidado_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='entrou',
            field=models.BooleanField(default=False),
        ),
    ]
