# Generated by Django 5.1.7 on 2025-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_confirmacao_entrou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='convidado',
            unique_together={('cpf', 'evento')},
        ),
    ]
