# Generated by Django 5.1.7 on 2025-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_convidado_convite_enviado_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='convidado',
            constraint=models.UniqueConstraint(fields=('email', 'evento'), name='unique_email_evento'),
        ),
    ]
