# Generated by Django 5.1.7 on 2025-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_convidado_unique_email_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
